### ISSUE TITLE
How do I config the .env files?

### ISSUE THREAD

**Issue by BrunoSette** [NV404/Emote#1]
I tried to test the app but got the error: 

[t [Error]: Your API key is invalid, please check you have copied it correctly.] {
  code: 'auth/invalid-api-key',
  a: null
}

**Comment by NV404** [comment]
create .env file in project root folder and try this structure

NEXT_PUBLIC_FIREBASE_API_KEY=YOUR VALUE
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=YOUR VALUE
NEXT_PUBLIC_FIREBASE_PROJECT_ID=YOUR VALUE
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=YOUR VALUE
NEXT_PUBLIC_FIREBASE_SENDER_ID=YOUR VALUE
NEXT_PUBLIC_FIREBASE_APP_ID=YOUR VALUE

**Comment by BrunoSette** [comment]
thank you

**Comment by NV404** [comment]
closing this issue
